### ISSUE TITLE
Prod - auth issue? 

### ISSUE THREAD

**Issue by VeeUye** [VeeUye/playdate-frontend#2]
Signing into prod causes an infinite loader. 
My profile not accessible but my events is.

Working locally fine

**Comment by ejmadkins** [comment]
I've just tried signing up with a new user, that completes successfully.  I then logged out and back in again a few times with the new user, on a few of  sign in attempts the loader was present for ~5 secs before the my profile page loads.  Can you double check to see if it's an issue with it being slow as opposed to not loading successfully at all?  Regardless if it is the former, I think we need to look into why as it's a pretty based user experience.

**Comment by VeeUye** [comment]
Followed the steps as above - no dice.
Getting a 400 bad request in the console.
This is prod so should have nothing to do with local set up
<img width="617" alt="Screenshot 2022-11-08 at 17 12 03" src="https://user-images.githubusercontent.com/97988558/200631166-a28835cb-3788-4f49-871e-eb9f85bfa564.png">

**Comment by VeeUye** [comment]
I've tried logging in again with a new test account and it seems to be working ok (!!)
I noticed I had another tab open with the app running in it and so closed these before retrying.
This might be worth keeping in mind as we refactor. It may be that having two or more instances of the app borks the auth.
